name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Build ứng dụng Android với Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Tải file APK lên Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TraCuuHoSo-APK
          path: bin/*.apk
          
