name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt và Build APK với Kivy Action
        uses: kivy/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Lưu trữ file APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: ${{ steps.buildozer.outputs.filename }}
          retention-days: 7
          
